[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  included_files = ["data/activities/**/*.json", "data/shows/**/*.json", "data/sc-theater-companies.json", "data/sc-theater-venues.json"]

[context.dev.environment]
  GITHUB_BRANCH = "dev"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
